stages:  
   - build  
   - deploy
build prod:  
   image: node:10.15.0-stretch  
   stage: build  
   only:    
      - tags  
   script:    
      # Install vuecli    
      - npm install -g @vue/cli@latest    
      # Install dependencies    
      - npm install    
      # Build App    
      - npm run build  
   artifacts:    
      paths:      
         # Build folder      
         - dist/    
      expire_in: 1 hour   